# Generated by Django 5.2.9 on 2025-12-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendance_certificate_evaluation_joinedparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='semester',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
    ]
